BracProject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Security;
using BracProject.Models;

namespace BracProject.Controllers
{
    public class LoginController : ApiController
    {
        private MySqlCon db = new MySqlCon();

        // GET: api/login
        public string Get()
        {
            return "value";
        }

        // GET: api/login/5
        public string Get(int id)
        {
            return "Empty";
        }

        // POST: api/login
        public object Post([FromBody]FormDataCollection formbody)
        {
            string userName = formbody.GetValues("user_name")[0];
            string password = formbody.GetValues("password")[0];
            string fcm_token = formbody.GetValues("fcm_token")[0];

           // string decode_password = FormsAuthentication.HashPasswordForStoringInConfigFile(password, "md5");

            bool isUserAval = db.Member_Data.Where(us => us.user_name == userName).Any();

            string[] UserLocations = { };

            if (isUserAval)
            {
                var Query = db.Member_Data.Where(l => l.user_name == userName && l.password == password);
                var result = Query.FirstOrDefault<MemberModel>();
                if (result != null)
                {
                    string usertype = string.Empty;
                    if(result.type==1)
                    {
                        usertype = "1";
                    }
                    else if(result.type==2)
                    {
                        usertype = "0";
                    }

                    var data = new
                    {
                        success = true,
                        user = new
                        {
                            id = result.id,
                            name = result.name,
                            user_name = result.user_name,
                            user_type= usertype,
                            email = "",
                            mobile = result.mobile_no,
                            created_at = result.created_at.ToString("dd/MM/yyyy") + " " + result.created_at.ToString("HH:m"),
                            updated_at = result.updated_at.ToString("dd/MM/yyyy") + " " + result.updated_at.ToString("HH:m")
                        },
                        UserLocations,
                        token = "test"
                    };
                    return data;
                }
                else
                {
                    var data = new
                    {
                        success = false,
                        message = "Login faild. Please check the email address and password!"
                    };
                    return data;
                }
            }
            else
            {
                var data = new
                {
                    success = false,
                    message = "Login faild. Please check your user name!"
                };
                return data;
            }
        }

        // PUT: api/login/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/login/5
        public void Delete(int id)
        {
        }
    }
}

BracProject/Controllers/WebLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using BracProject.Models;

using Newtonsoft.Json;

namespace BracProject.Controllers
{
    public class WebLoginController : Controller
    {
        private MySqlCon db = new MySqlCon();

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Index(LoginModel user)
        {
            string message = string.Empty;
            if (String.IsNullOrEmpty(user.user_name) || String.IsNullOrEmpty(user.password))
            {
                ViewBag.Message = "Username and/or password is incorrect.";
            }
            else
            {

               // String password = FormsAuthentication.HashPasswordForStoringInConfigFile(user.password, "md5");
                var userDetails = db.Member_Data.Where(lo => lo.user_name == user.user_name && lo.password == user.password).FirstOrDefault<MemberModel>();

                if (userDetails == null)
                {
                    ViewBag.Message = "Username and/or password is incorrect.";
                }
                else
                {
                    Session["memberType"] = userDetails.MemberType.ToString();
                    FormsAuthentication.SetAuthCookie(user.email, false);
                    //string roles = UserRoleString(userDetails.id);
                    var authTicket = new FormsAuthenticationTicket(1, user.user_name, DateTime.Now, DateTime.Now.AddMinutes(20), false, "");
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    return RedirectToAction("../dashboard");
                }
            }

            return View(user);
        }



        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();


            return RedirectToAction("/");
        }

        //public string UserRoleString(int userID)
        //{
        //    string userRole = null;
        //    var result = db.UserRoleList_Data.Where(ur => ur.USER_ID == userID).ToList<UserRoleListModel>();
        //    if (result.Count() != 0)
        //    {
        //        foreach (var entity in result)
        //        {
        //            string modelName = db.ModuleList_Data.Where(ml => ml.ID == entity.MODULE_ID).FirstOrDefault<ModuleListModel>().SHORT_NAME;
        //            if (entity.U_VIEW == 1) 
        //            {
        //                userRole =modelName+"View"+","+userRole; 
        //            }
        //            if (entity.U_ADD == 1)
        //            {
        //                userRole = modelName + "Add" + "," + userRole;
        //            }
        //            if (entity.U_EDIT == 1)
        //            {
        //                userRole = modelName + "Edit" + "," + userRole;
        //            }
        //            if (entity.U_DELETE == 1)
        //            {
        //                userRole = modelName + "Del" + "," + userRole;
        //            }
        //        }
        //    }

        //    userRole = userRole.TrimEnd(',');
        //    return userRole;
        //}
    }
}

BracProject/Views/WebLogin/Index.cshtml
@{
    Layout = null;
}
@model BracProject.Models.LoginModel

<!DOCTYPE html>
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="TAREQ">
    <title>Login - STH</title>
    <link rel="apple-touch-icon" sizes="60x60" href="/Content/tm-th-assets/images/ico/apple-icon-60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/Content/tm-th-assets/images/ico/apple-icon-76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/Content/tm-th-assets/images/ico/apple-icon-120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/Content/tm-th-assets/images/ico/apple-icon-152.png">
    <link rel="shortcut icon" type="image/x-icon" href="/Content/tm-th-assets/images/ico/favicon.ico">
    <link rel="shortcut icon" type="image/png" href="/Content/tm-th-assets/images/ico/favicon-32.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/bootstrap.css">
    <!-- font icons-->
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/fonts/icomoon.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/fonts/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/vendors/css/extensions/pace.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN ROBUST CSS-->
    <link rel="stylesheet" type="text/css" href="/Content/tm-th--assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/app.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/colors.css">
    <!-- END ROBUST CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/core/menu/menu-types/vertical-overlay-menu.css">
    <link rel="stylesheet" type="text/css" href="/Content/tm-th-assets/css/pages/login-register.css">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="/Content/tm-assets/css/style.css">
    <!-- END Custom CSS-->
</head>
<body data-open="click" data-menu="vertical-menu" data-col="1-column" class="vertical-layout vertical-menu 1-column  blank-page blank-page">
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <section class="flexbox-container">
                    <div class="col-md-4 offset-md-4 col-xs-10 offset-xs-1  box-shadow-2 p-0">
                        <div class="card border-grey border-lighten-3 m-0">
                            <div class="card-header no-border">
                                <div class="card-title text-xs-center">
                                    <div class="p-1"><img src="/Content/tm-th-assets/images/logo/robust-logo-light.png" alt="branding logo"></div>
                                </div>
                            </div>
                            <div class="card-body collapse in">
                                <div class="card-block">
                                    @if (ViewBag.Message != null)
                                    {
                                        <div class="card-text">
                                            <div class="alert bg-info alert-icon-right alert-arrow-right alert-dismissible fade in" role="alert">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                                @ViewBag.Message
                                            </div>
                                        </div>
                                    }
                                    @using (Html.BeginForm("Index", "WebLogin", FormMethod.Post))
                                    {
                                        @Html.ValidationSummary(true)
                                        @Html.AntiForgeryToken()
                                        <fieldset class="form-group position-relative has-icon-left mb-0">
                                            @Html.TextBoxFor(model => model.user_name, new { placeholder = "User Name", @class = "form-control form-control-lg input-lg" })
                                            <div class="form-control-position">
                                                <i class="icon-head"></i>
                                            </div>
                                            @Html.ValidationMessageFor(model => model.user_name)
                                        </fieldset>
                                        <fieldset class="form-group position-relative has-icon-left">
                                            @Html.PasswordFor(model => model.password, new { placeholder = "Password", @class = "form-control form-control-lg input-lg" })
                                            <div class="form-control-position">
                                                <i class="icon-key3"></i>
                                            </div>
                                            @Html.ValidationMessageFor(model => model.password)
                                        </fieldset>
                                        <fieldset class="form-group row"></fieldset>
                                        <button type="submit" class="btn btn-primary btn-lg btn-block"><i class="icon-unlock2"></i> Login</button>
                                    }
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="">
                                    <p style="font-size:11px" class="float-sm-right text-xs-center m-0">Copyright  &copy; 2018 BRAC (STH)  <br /> Developed by: <a href="" class="card-link"></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <!-- BEGIN VENDOR JS-->
    <script src="/Content/tm-th-assets/js/core/libraries/jquery.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/tether.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/js/core/libraries/bootstrap.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/unison.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/blockUI.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/jquery.matchHeight-min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/ui/screenfull.min.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/vendors/js/extensions/pace.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN ROBUST JS-->
    <script src="/Content/tm-th-assets/js/core/app-menu.js" type="text/javascript"></script>
    <script src="/Content/tm-th-assets/js/core/app.js" type="text/javascript"></script>
    <!-- END ROBUST JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <!-- END PAGE LEVEL JS-->
</body>
</html>

BracProject/Views/WebLogin/_ExternalLoginsListPartial.cshtml
@model lged_api.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "WebLogin", new { ReturnUrl = Model.ReturnUrl })) {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders) {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}

BracProject/Views/WebLogin/login.cshtml
@using BracProject.Models
@model LoginViewModel

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>Welcome| Login Page</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta content="" name="description" />
    <meta content="The Messenger" name="author" />

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/style-responsive.min.css" rel="stylesheet" />

</head>
<body>
    <div class="login-cover">
        <div class="login-cover-image"><img src="~/Content/img/bg.jpg" data-id="login-cover-image" alt="" /></div>
        <div class="login-cover-bg"></div>
    </div>
    <div id="page-container" class="fade">
        <div class="login login-v2" data-pageload-addclass="animated fadeIn">
            <div class="login-header">
                <div class="brand"> <span class="logo"></span> LGED <small>Mobile Application for Field-work Inspection</small> </div>
            </div>
            <div class="login-content">

            </div>
            @using (Html.BeginForm("login", "WebLogin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.EMAIL, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.EMAIL, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.EMAIL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PASSWORD, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.PASSWORD, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PASSWORD, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.REMEMBERME)
                            @Html.LabelFor(m => m.REMEMBERME)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
            <div class="col-md-4">
                <section id="socialLoginForm">
                    @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                </section>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/apps.min.js"></script>
    <script>$(document).ready(function() {
            App.init();
            TableManageCombine.init();
});</script>

</body>
</html>